### ISSUE TITLE
Storybookのビルドでエラーが発生する

### ISSUE THREAD

**Issue by gigi434** [gigi434/ReStartNow#146]
### 概要
コンポーネントカタログであるStorybook上で作成した関数コンポーネントを確認しようとビルドしたところエラーを確認した。

### 実際のログ
<details><summary>Details</summary>
<p>

```shell
node@4d56c27bf122:~/nextjs$ npm run storybook

> nextjs@0.1.0 storybook
> storybook dev -p 6006

@storybook/cli v7.6.17

WARN Could not resolve addon "storybook-css-modules", skipping. Is it installed?
info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

WARN Could not resolve addon "storybook-css-modules", skipping. Is it installed?
info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
info => Serving static files from ././public at /
info => Starting manager..
WARN No story files found for the specified pattern: @(stories|src)/**/*.mdx
✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "UNHANDLED_ERRORS_WHILE_PLAYING"

    node_modules/@storybook/preview-api/dist/index.mjs:4:488:
      4 │ ...ION, STORY_RENDER_PHASE_CHANGED, STORY_ERRORED, PLAY_FUNCTION_THREW_EXCEPTION, UNHANDLED_ERRORS_WHILE_PLAYING, DOCS_RENDERED } from '@storybook/core-events';
        ╵                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "global-externals:@storybook/components" for import "EmptyTabContent"

    node_modules/@storybook/addon-controls/node_modules/@storybook/blocks/dist/index.mjs:4:178:
      4 │ ...utton, Link, ResetWrapper, Code, nameSpaceClassNames, H3, H2, Loader, EmptyTabContent, TabsState, ErrorFormatter, getStoryHref, WithTooltipPure } from '@s...
        ╵                                                                          ~~~~~~~~~~~~~~~

SB_CORE-SERVER_0004 (NoMatchingExportError): There was an exports mismatch error when trying to build Storybook.
Please check whether the versions of your Storybook packages match whenever possible, as this might be the cause.

Problematic example:
{ "@storybook/react": "7.5.3", "@storybook/react-vite": "7.4.5", "storybook": "7.3.0" }

Correct example:
{ "@storybook/react": "7.5.3", "@storybook/react-vite": "7.5.3", "storybook": "7.5.3" }

Please run `npx storybook@latest doctor` for guidance on how to fix this issue.
    at buildOrThrow (./node_modules/@storybook/core-server/dist/index.js:60:8467)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:120:1397)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:65:3948)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:514:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:529:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN Could not resolve addon "storybook-css-modules", skipping. Is it installed?
info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
✖ Would you like to help improve Storybook by sending anonymous crash reports? … yes
``` 

</p>
</details> 

### 目標
ビルドエラーの解消およびStorybook上での関数コンポーネント確認ができる

**Comment by gigi434** [comment]
Storybook7.1.1を再度設定することで回避しようとしたが、公式ドキュメントを参照しても404エラーが出るためバージョン8にする
https://release-7-0--storybook-frontpage.netlify.app/docs/7.1/get-started/install

**Comment by gigi434** [comment]
下記Githubのイシューのコメントを参考にStorybookアドオンのバージョンを7.1.1に揃えるとビルドが正常に行われる
https://github.com/storybookjs/storybook/issues/22252#issuecomment-1522860337

Storybookの8へのバージョンアップを行うとMSWの設定でエラーが出るため上記設定変更でクローズする

**Comment by gigi434** [comment]
目標を達成したためクローズ
